# Generated by Django 6.1 on 2026-08-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cylinder',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cylindertransaction',
            name='destination',
            field=models.CharField(blank=True, choices=[('FIELD', 'Field'), ('WAREHOUSE', 'Warehouse'), ('MASS SCAN', 'Mass Scan')], max_length=20, null=True),
        ),
    ]
